- name: Install Docker prerequisites
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker.io
    - docker-compose

- name: Add dokwerker user
  user:
    name: dokwerker
    groups: docker
    append: yes

- name: Enable docker service
  systemd:
    name: docker
    enabled: true
    state: started

- name: Set hostname
  hostname:
    name: terminal
